#Exercise 3.8
Places=["yahore","zarachi","islamabad"]
#print("Enter Places  you want to visit")
#for i in range(5):
#    Places.append(input())
print(Places)
print("sorted list:")
print(sorted(Places))
print("Original list:")
print(Places)
print("Reverse sorted list:")
print(sorted(Places,reverse=True))
print("Original list:")
print(Places)
print("list in reversed order:")
Places.reverse()
print(Places)
print("Original List again:")
Places.reverse()
print(Places)
print("permanantly sorted list:")
Places.sort()
print(Places)
print("reversed permanantly sorted :")
Places.sort(reverse=True)
print(Places)
